[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]

[rpc_endpoints]
mainnet = "https://eth.llamarpc.com"
sepolia = "${SEPOLIA_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
optimism_sepolia = "${OPTIMISM_SEPOLIA_RPC_URL}"
flow_testmest = ""


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
